language: python
python:
  - "2.7"
# command to run tests
script:
  - source venv.sh
  - make install
  - venv create mynewenv
  - venv c mynewcenv
  - venv export mynewenv
  - _virtualenv 2.6 c mynew26env
  - python tests/venv_tests.py